### ISSUE TITLE
Scrollbar on the left navigation shifts in Firefox

### ISSUE THREAD

**Issue by Leva7** [CREATORSNEVERDIE/renaissance#1]
The issue occurs on the Documenation page

The following three screenshots show the scrollbar as I scroll through the docs page. As you can see, it shifts right and even overlaps the text
![screenshot-2018-1-14 renaissance - the freshest css framework](https://user-images.githubusercontent.com/15035286/34914581-1395d814-f937-11e7-95fb-a15d280c1d1f.png)
![screenshot-2018-1-14 renaissance - the freshest css framework 1](https://user-images.githubusercontent.com/15035286/34914582-167dde64-f937-11e7-9cda-486e0502bf9b.png)
![screenshot-2018-1-14 renaissance - the freshest css framework 2](https://user-images.githubusercontent.com/15035286/34914584-19314bc8-f937-11e7-84b4-62e9c358676d.png)

Issue seen on Ubuntu 16.04 in Firefox 57.0.4 (latest)

**Comment by vazh** [comment]
Same thing confirmed on eOS 0.4 in Chrome Version 63.0.3239.84

**Comment by dillonraphael** [comment]
This was more a landing page issue then the actual framework. Although it does open thought on how the grid is utilized. I'm closing this issue, as I did push an update to the landing page it self for sidebar fixes. Hopefully this helps.
